### PR TITLE
WIP: Add TBH Content Compendia

### PR DESCRIPTION
**Pull request by atomdmac**
Adds the classes, spells, equipment, etc. as compendia.

## TODO
* [ ] Add roll tables for OofA and NPC reactions
* [x] Fix `arcane-spells.db` IDs.

### CODE REVIEW

**Review by free-beer — COMMENTED** [review]
Hey @atomdmac , seems someone has been busy!

One concern I have here is the possibility that we may be violating copyright by placing this stuff into the repository. I've never contacted David Black for permissions for this stuff, so I guess I could also be in violation for using the name but the system mechanics can't be protected (as long as I don't reproduce the content verbatim). I'll have to think about this one.

**Comment by atomdmac** [comment]
@free-beer Yikes, yeah that's a good point.  I got a little out over my skies 😬 .  I'm happy to delete this public branch while we figure that stuff out.

**Comment by atomdmac** [comment]
FYI: Looks like I'm not able to outright delete this PR but I _did_ remove the branch on my fork.

**Comment by ryanSN** [comment]
@free-beer @woodzer 
Got yah your access. lets see black hack in the list! 🤘🏻 

Screen Shot 2022-05-06 at 9 57 01 AM

**Comment by free-beer** [comment]
Ta, will look into that as soon as I can.

**Comment by atomdmac** [comment]
@free-beer Howdy!  Just wanted to check in with you on this one.  Is there anything I can do to help get this merged?

**Comment by free-beer** [comment]
Apologies, had much on that meant this got completely forgotten about. I can merge this but then I will have to do a release to make it actually available in Foundry.

**Comment by free-beer** [comment]
Okay @atomdmac , I think I've correctly pushed out version 0.6.0 which should include your content.

**Pull request merged**
